remote_theme: eheisig/forty-jekyll-theme

title: eheisig.com
description: Enjoy your stay :)

markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
